g

diff --git a/.github/workflows/deploy_on_int.yml b/.github/workflows/deploy_on_int.yml
--- a/.github/workflows/deploy_on_int.yml
+++ b/.github/workflows/deploy_on_int.yml
@@ -92,9 +92,7 @@ jobs:
           coverage_warnings=$(echo "$result" | jq -r '.result.codeCoverageWarnings[]?.message' 2>/dev/null)
           if [ -n "$coverage_warnings" ]; then
             while IFS= read -r warning; do
-              echo "::error::Code Coverage Issue: $warning"
-            done <<< "$coverage_warnings"
-            exit 1
+              echo "::error::Code Coverage Issue: $warning" && exit 1
           fi
 
           # Si tout est OK
