u

diff --git a/.github/workflows/deploy_on_int.yml b/.github/workflows/deploy_on_int.yml
--- a/.github/workflows/deploy_on_int.yml
+++ b/.github/workflows/deploy_on_int.yml
@@ -74,21 +74,31 @@ jobs:
           
       - name: Deploy delta changes
         run: |
-          result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level NoTestRun --json)
-
-          # if [ -z "${APEX_TESTS}" ]; then
-          #   echo "No tests specified."
-          #   result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level NoTestRun --json 2>&1)
-          # elif [ "${APEX_TESTS}" == "all" ]; then
-          #   echo "Run all local tests."
-          #   result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level RunLocalTests --json 2>&1)
-          # else
-          #   echo "Run specific tests."
-          #   result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level RunSpecifiedTests --runtests "${APEX_TESTS}" --json 2>&1)
-          # fi
+          if [ -z "${APEX_TESTS}" ]; then
+            echo "No tests specified."
+            result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level NoTestRun --json)
+          elif [ "${APEX_TESTS}" == "all" ]; then
+            echo "Run all local tests."
+            result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level RunLocalTests --json)
+          else
+            echo "Run specific tests."
+            result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level RunSpecifiedTests --runtests "${APEX_TESTS}" --json)
+          fi
 
           # Afficher le résultat brut pour débogage
           echo "Deployment result: $result"
+
+          if ! echo "$result" | jq -e . >/dev/null 2>&1; then
+            echo "::error::Invalid JSON response from deployment command."
+            exit 1
+          fi
+
+          echo "Check code coverage warnings."
+          coverage_warnings=$(echo "$result" | jq -r '.result.codeCoverageWarnings' 2>/dev/null)
+          if [ -n "$coverage_warnings" ]; then
+            echo "::error::Code coverage issue."
+            exit 1
+          fi
 
       - name: Cleanup temporary files
         run: rm -f pr_body.txt testsToRun.txt SF_INTEGRATION_URL.txt
