e

diff --git a/.github/workflows/deploy_on_int.yml b/.github/workflows/deploy_on_int.yml
--- a/.github/workflows/deploy_on_int.yml
+++ b/.github/workflows/deploy_on_int.yml
@@ -88,23 +88,17 @@ jobs:
           # Afficher le résultat brut
           echo "Deployment result: $result"
 
-          # Vérifier si le déploiement a réussi ou échoué
-          success=$(echo "$result" | jq -r '.status' 2>/dev/null)
-          if [ "$success" != "Succeeded" ]; then
-            echo "::error ::Deployment failed."
-          fi
-
-          # Extraire les avertissements de couverture de code
-          coverage_warning=$(echo "$result" | jq '.result.codeCoverageWarnings' 2>/dev/null)
-          if [ "$coverage_warning" != "null" ]; then
-            echo "::error ::Merging is blocked due to insufficient test coverage."
-            echo "Coverage issues: $coverage_warning" >> $GITHUB_ENV
+          # Vérifier les avertissements de couverture de code
+          coverage_warnings=$(echo "$result" | jq -r '.result.codeCoverageWarnings[]?.message' 2>/dev/null)
+          if [ -n "$coverage_warnings" ]; then
+            while IFS= read -r warning; do
+              echo "::error ::Code Coverage Issue: $warning"
+            done <<< "$coverage_warnings"
+            exit 1
           fi
 
           # Si tout est OK
-          echo "Deployment check passed without issues."
-
-      
+          echo "Deployment check passed without issues."      
 
       - name: Cleanup temporary files
         run: rm -f pr_body.txt testsToRun.txt SF_INTEGRATION_URL.txt
