i

diff --git a/.github/workflows/deploy_on_int.yml b/.github/workflows/deploy_on_int.yml
--- a/.github/workflows/deploy_on_int.yml
+++ b/.github/workflows/deploy_on_int.yml
@@ -86,12 +86,20 @@ jobs:
             echo "$result"
           fi
 
-          echo "Check code coverage warnings."
-          coverage_warnings=$(echo "$result" | jq -r '.result.codeCoverageWarnings' 2>/dev/null)
+          coverage_warnings=$(echo "$result" | jq -r '.result.codeCoverageWarnings[]?.message' 2>/dev/null)
           if [ -n "$coverage_warnings" ]; then
-            echo "::error::Code coverage issue."
+            while IFS= read -r warning; do
+              echo "::error::Code Coverage Issue: $warning"
+            done <<< "$coverage_warnings"
             exit 1
           fi
+
+          # echo "Check code coverage warnings."
+          # coverage_warnings=$(echo "$result" | jq -r '.result.codeCoverageWarnings' 2>/dev/null)
+          # if [ -n "$coverage_warnings" ]; then
+          #   echo "::error::Code coverage issue: $result.codeCoverageWarnings[].message"
+          #   exit 1
+          # fi
 
       - name: Cleanup temporary files
         run: rm -f pr_body.txt testsToRun.txt SF_INTEGRATION_URL.txt
